//
//  OptionsScreenViewControllerPresenter.swift
//  ControlGastos
//
//  Created Cesar Cabrera Jacobo on 14/12/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class OptionsScreenViewControllerPresenter: OptionsScreenViewControllerPresenterProtocol {

    weak private var view: OptionsScreenViewControllerViewProtocol?
    var interactor: OptionsScreenViewControllerInteractorProtocol?
    private let router: OptionsScreenViewControllerWireframeProtocol

    init(interface: OptionsScreenViewControllerViewProtocol, interactor: OptionsScreenViewControllerInteractorProtocol?, router: OptionsScreenViewControllerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
