//
//  OptionsScreenViewControllerProtocols.swift
//  ControlGastos
//
//  Created Cesar Cabrera Jacobo on 14/12/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol OptionsScreenViewControllerWireframeProtocol: class {

}
//MARK: Presenter -
protocol OptionsScreenViewControllerPresenterProtocol: class {

}

//MARK: Interactor -
protocol OptionsScreenViewControllerInteractorProtocol: class {

  var presenter: OptionsScreenViewControllerPresenterProtocol?  { get set }
}

//MARK: View -
protocol OptionsScreenViewControllerViewProtocol: class {

  var presenter: OptionsScreenViewControllerPresenterProtocol?  { get set }
}
