//
//  OptionsScreenViewControllerRouter.swift
//  ControlGastos
//
//  Created Cesar Cabrera Jacobo on 14/12/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class OptionsScreenViewControllerRouter: OptionsScreenViewControllerWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = OptionsScreenViewControllerViewController(nibName: nil, bundle: nil)
        let interactor = OptionsScreenViewControllerInteractor()
        let router = OptionsScreenViewControllerRouter()
        let presenter = OptionsScreenViewControllerPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
