//
//  OptionsScreenViewControllerInteractor.swift
//  ControlGastos
//
//  Created Cesar Cabrera Jacobo on 14/12/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class OptionsScreenViewControllerInteractor: OptionsScreenViewControllerInteractorProtocol {

    weak var presenter: OptionsScreenViewControllerPresenterProtocol?
}
