//
//  AccountScreenViewControllerPresenter.swift
//  ControlGastos
//
//  Created Cesar Cabrera Jacobo on 14/12/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AccountScreenViewControllerPresenter: AccountScreenViewControllerPresenterProtocol {

    weak private var view: AccountScreenViewControllerViewProtocol?
    var interactor: AccountScreenViewControllerInteractorProtocol?
    private let router: AccountScreenViewControllerWireframeProtocol

    init(interface: AccountScreenViewControllerViewProtocol, interactor: AccountScreenViewControllerInteractorProtocol?, router: AccountScreenViewControllerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
