//
//  AccountScreenViewControllerProtocols.swift
//  ControlGastos
//
//  Created Cesar Cabrera Jacobo on 14/12/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol AccountScreenViewControllerWireframeProtocol: class {

}
//MARK: Presenter -
protocol AccountScreenViewControllerPresenterProtocol: class {

}

//MARK: Interactor -
protocol AccountScreenViewControllerInteractorProtocol: class {

  var presenter: AccountScreenViewControllerPresenterProtocol?  { get set }
}

//MARK: View -
protocol AccountScreenViewControllerViewProtocol: class {

  var presenter: AccountScreenViewControllerPresenterProtocol?  { get set }
}
