//
//  UserScreenViewControllerPresenter.swift
//  ControlGastos
//
//  Created Cesar Cabrera Jacobo on 14/12/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UserScreenViewControllerPresenter: UserScreenViewControllerPresenterProtocol {

    weak private var view: UserScreenViewControllerViewProtocol?
    var interactor: UserScreenViewControllerInteractorProtocol?
    private let router: UserScreenViewControllerWireframeProtocol

    init(interface: UserScreenViewControllerViewProtocol, interactor: UserScreenViewControllerInteractorProtocol?, router: UserScreenViewControllerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
