//
//  UserScreenViewControllerProtocols.swift
//  ControlGastos
//
//  Created Cesar Cabrera Jacobo on 14/12/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol UserScreenViewControllerWireframeProtocol: class {

}
//MARK: Presenter -
protocol UserScreenViewControllerPresenterProtocol: class {

}

//MARK: Interactor -
protocol UserScreenViewControllerInteractorProtocol: class {

  var presenter: UserScreenViewControllerPresenterProtocol?  { get set }
}

//MARK: View -
protocol UserScreenViewControllerViewProtocol: class {

  var presenter: UserScreenViewControllerPresenterProtocol?  { get set }
}
