//
//  MovementScreenViewControllerProtocols.swift
//  ControlGastos
//
//  Created Cesar Cabrera Jacobo on 14/12/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MovementScreenViewControllerWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol MovementScreenViewControllerPresenterProtocol: AnyObject {

}

//MARK: Interactor -
protocol MovementScreenViewControllerInteractorProtocol: AnyObject {

  var presenter: MovementScreenViewControllerPresenterProtocol?  { get set }
}

//MARK: View -
protocol MovementScreenViewControllerViewProtocol: AnyObject {

  var presenter: MovementScreenViewControllerPresenterProtocol?  { get set }
}
