//
//  MovementScreenViewControllerPresenter.swift
//  ControlGastos
//
//  Created Cesar Cabrera Jacobo on 14/12/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MovementScreenViewControllerPresenter: MovementScreenViewControllerPresenterProtocol {

    weak private var view: MovementScreenViewControllerViewProtocol?
    var interactor: MovementScreenViewControllerInteractorProtocol?
    private let router: MovementScreenViewControllerWireframeProtocol

    init(interface: MovementScreenViewControllerViewProtocol, interactor: MovementScreenViewControllerInteractorProtocol?, router: MovementScreenViewControllerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
