//
//  MovementScreenViewControllerViewController.swift
//  ControlGastos
//
//  Created Cesar Cabrera Jacobo on 14/12/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MovementScreenViewControllerViewController: UIViewController, MovementScreenViewControllerViewProtocol {

	var presenter: MovementScreenViewControllerPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
